# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "cellprofiler_segcheck"
description: Runs CellProfiler segmentation check pipeline to validate image segmentation quality and generate quality control outputs
keywords:
  - cellprofiler
  - segmentation
  - quality control
  - cell painting
  - microscopy
tools:
  - "cellprofiler":
      description: "CellProfiler is free, open-source software for quantitative analysis of biological images."
      homepage: "https://cellprofiler.org/"
      documentation: "https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.8/index.html"
      tool_dev_url: "https://github.com/CellProfiler/CellProfiler"
      doi: "https://doi.org/10.1186/s12859-021-04344-9"
      licence: ["BSD-3-clause"]
      identifier: biotools:CellProfiler

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - corr_images:
        type: file
        description: Corrected microscopy images for segmentation quality checking
        pattern: "*.{tif,tiff,png}"
        ontologies:
          - edam: http://edamontology.org/format_3547
    - image_metas:
        type: list
        description: "List of image metadata maps containing plate, well, site, channels, filename information"
  - segcheck_cppipe:
      type: file
      description: CellProfiler pipeline file (.cppipe) for segmentation checking
      pattern: "*.cppipe"
      ontologies:
        - edam: http://edamontology.org/format_2330
  - range_skip:
      type: integer
      description: Number of images to skip when generating load data CSV for processing subset

output:
  - segcheck_res:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.csv":
          type: file
          description: CellProfiler segmentation check measurements in CSV format
          pattern: "*.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
      - "*.png":
          type: file
          description: Quality control images showing segmentation results
          pattern: "*.png"
          ontologies:
            - edam: http://edamontology.org/format_3603
  - load_data_csv:
      - "load_data.csv":
          type: file
          description: "Generated load_data.csv file used by CellProfiler to load and organize input images"
          pattern: "load_data.csv"
          ontologies:
            - edam: "http://edamontology.org/format_3752" # CSV
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
          ontologies:
            - edam: http://edamontology.org/format_3750

authors:
  - "@FloWuenne"
maintainers:
  - "@FloWuenne"
