# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "cellprofiler_load_data_csv_with_illum"
## TODO nf-core: Add a description of the subworkflow and list keywords
description: |
  Loads image data from CSV files and applies illumination correction using CellProfiler.
  This subworkflow prepares input data for downstream image analysis by generating
  illumination-corrected images and associated metadata.
keywords:
  - cellprofiler
  - illumination correction
  - image analysis
  - csv
  - microscopy
## TODO nf-core: Add a list of the modules and/or subworkflows used in the subworkflow
components:
  - cellprofiler/load_data_csv
  - cellprofiler/illumination_correction
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - ch_csv:
      type: file
      description: |
        The input channel containing CSV files with image metadata and paths.
        Structure: [ val(meta), path(csv) ]
      pattern: "*.csv"
  - ch_images:
      type: file
      description: |
        The input channel containing raw microscopy image files.
        Structure: [ val(meta), path(image) ]
      pattern: "*.tif"
  - ch_illum_corr:
      type: file
      description: |
        The input channel containing illumination correction images.
        Structure: [ val(meta), path(illum_corr) ]
      pattern: "*illum*.tif"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - corrected_images:
      type: file
      description: |
        Channel containing illumination-corrected image files.
        Structure: [ val(meta), path(corrected_image) ]
      pattern: "*_illumcorr.tif"
  - output_csv:
      type: file
      description: |
        Channel containing output CSV files with updated image metadata.
        Structure: [ val(meta), path(csv) ]
      pattern: "*_output.csv"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@FloWuenne"
maintainers:
  - "@FloWuenne"
