# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "cellprofiler_preprocess"
description: Performs SBS (Sequencing by Synthesis) preprocessing on barcoding images using CellProfiler, including image averaging across cycles, and feature extraction
keywords:
  - cellprofiler
  - image_analysis
  - preprocessing
  - barcoding
  - sbs
  - sequencing_by_synthesis
tools:
  - "cellprofiler":
      description: "CellProfiler is free, open-source software for quantitative analysis of biological images."
      homepage: "https://cellprofiler.org"
      documentation: "https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.8/index.html"
      tool_dev_url: "https://github.com/CellProfiler/CellProfiler"
      doi: "10.1371/journal.pbio.1000502"
      licence: ["BSD-3-clause"]
      identifier: biotools:CellProfiler

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', batch:'batch1', plate:'plate1', well:'A01', arm:'barcoding' ]`
  - corr_images:
      type: file
      description: Illumination-corrected images from SBS cycles for preprocessing
      pattern: "*.{tif,tiff,png}"
      ontologies:
        - edam: http://edamontology.org/format_3547 # Image format
  - preprocess_cppipe:
      type: file
      description: CellProfiler pipeline file (.cppipe) defining the preprocessing workflow for SBS images
      pattern: "*.cppipe"
      ontologies:
        - edam: http://edamontology.org/format_2330 # Text format

output:
  preprocess_res:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', batch:'batch1', plate:'plate1', well:'A01', arm:'barcoding' ]`
    - "*.csv":
        type: file
        description: CSV files containing preprocessing results including Cells, Nuclei, Image, and Experiment measurements from CellProfiler
        pattern: "*.csv"
        ontologies:
          - edam: http://edamontology.org/format_3752
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750

authors:
  - "@FloWuenne"
maintainers:
  - "@FloWuenne"
