# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "cellprofiler_illumcalc"
description: "Calculate illumination correction functions from microscopy images using CellProfiler"
keywords:
  - illumination_correction
  - cellprofiler
  - microscopy
  - image_processing
tools:
  - "cellprofiler":
      description: "CellProfiler is free, open-source software for quantitative analysis of biological images."
      homepage: "https://cellprofiler.org/"
      documentation: "https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.8/index.html"
      tool_dev_url: "https://github.com/CellProfiler/CellProfiler"
      doi: "https://doi.org/10.1186/s12859-021-04344-9"
      licence: ["BSD-3-clause"]
      identifier: biotools:CellProfiler

input:
  - - meta:
        type: map
        description: "Groovy Map containing sample information (e.g. batch, plate, arm, well)"
    - channels:
        type: string
        description: "Comma-separated list of channel names"
    - cycle:
        type: string
        description: "Cycle identifier or name"
    - images:
        type: file
        description: "Microscopy images for illumination correction calculation"
        pattern: "*.{tiff,tif,png,jpg}"
    - image_metas:
        type: list
        description: "List of image metadata maps containing plate, well, site, channels, filename information"
  - illumination_cppipe:
      type: file
      description: "CellProfiler pipeline file for illumination correction calculation"
      pattern: "*.{cppipe,template}"
  - has_cycles:
      type: boolean
      description: "Whether the experiment includes multiple cycles"
output:
  - illumination_corrections:
      - meta:
          type: map
          description: "Groovy Map containing sample information (e.g. batch, plate, arm, well)"
      - "*.npy":
          type: file
          description: "Illumination correction files in numpy format"
          pattern: "*.npy"
  - load_data_csv:
      - "load_data.csv":
          type: file
          description: "Generated load_data.csv file used by CellProfiler to load and organize input images"
          pattern: "load_data.csv"
          ontologies:
            - edam: "http://edamontology.org/format_3752" # CSV
  - versions:
      - versions.yml:
          type: file
          description: "File containing software versions"
          pattern: "versions.yml"
authors:
  - "@FloWuenne"
maintainers:
  - "@FloWuenne"
