# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fiji_stitchcrop"
description: Stitch multi-site microscopy images and crop into tiles using ImageJ/Fiji
keywords:
  - microscopy
  - image processing
  - stitching
  - cropping
  - fiji
  - imagej
tools:
  - "fiji":
      description: "ImageJ distribution with batteries included"
      homepage: "https://fiji.sc/"
      documentation: "https://imagej.net/software/fiji/"
      tool_dev_url: "https://github.com/fiji/fiji"
      licence: "GPL-2.0-or-later"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', batch:'Batch1', plate:'Plate1', well:'A1' ]`
    - corrected_images:
        type: file
        description: Illumination-corrected TIFF images from multiple sites
        pattern: "*.{tif,tiff}"
        ontologies:
          - edam: http://edamontology.org/format_3547
  - stitch_script:
      type: file
      description: Jython script for Fiji to perform stitching and cropping operations
      pattern: "*.py"
      ontologies:
        - edam: http://edamontology.org/format_3996
  - round_or_square:
      type: string
      description: Acquisition pattern shape (round or square)
  - quarter_if_round:
      type: string
      description: Which quarter of the round pattern to process
  - overlap_pct:
      type: float
      description: Percentage of overlap between adjacent tiles
  - scalingstring:
      type: string
      description: Scaling factor for image processing
  - imperwell:
      type: integer
      description: Number of images per well
  - rows:
      type: integer
      description: Number of rows in the acquisition grid
  - columns:
      type: integer
      description: Number of columns in the acquisition grid
  - stitchorder:
      type: string
      description: Order in which to stitch tiles
  - tileperside:
      type: integer
      description: Number of tiles per side of the grid
  - final_tile_size:
      type: integer
      description: Final size of each tile after cropping (in pixels)
  - xoffset_tiles:
      type: integer
      description: X-axis offset for tile positioning
  - yoffset_tiles:
      type: integer
      description: Y-axis offset for tile positioning
  - compress:
      type: boolean
      description: Whether to compress output images
  - should_run:
      type: boolean
      description: Whether to run the stitching process

output:
  - stitched_images:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', batch:'Batch1', plate:'Plate1', well:'A1' ]`
      - "*.tiff":
          type: file
          description: Stitched full-well microscopy images created by combining multiple site images
          pattern: "stitched_images/*.{tif,tiff}"
          ontologies:
            - edam: http://edamontology.org/format_3547
  - tile_config:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', batch:'Batch1', plate:'Plate1', well:'A1' ]`
      - "TileConfiguration.txt":
          type: file
          description: Fiji Grid/Collection stitching tile configuration file containing image positions
          pattern: "stitched_images/TileConfiguration.txt"
          ontologies:
            - edam: http://edamontology.org/format_2330
  - cropped_images:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', batch:'Batch1', plate:'Plate1', well:'A1' ]`
      - "*.tiff":
          type: file
          description: Cropped tile images extracted from stitched images for downstream analysis
          pattern: "cropped_images/*.{tif,tiff}"
          ontologies:
            - edam: http://edamontology.org/format_3547
  - downsampled_images:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', batch:'Batch1', plate:'Plate1', well:'A1' ]`
      - "*.tiff":
          type: file
          description: Downsampled (10x) versions of stitched images for quality control and visualization
          pattern: "downsampled_images/*.{tif,tiff}"
          ontologies:
            - edam: http://edamontology.org/format_3547
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
          ontologies:
            - edam: http://edamontology.org/format_3750

authors:
  - "@FloWuenne"
maintainers:
  - "@FloWuenne"
